import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import StoreProvider from "./StoreProvider";
import { Suspense } from "react";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import FooterComponent from "@/components/Footer/FooterComponent";
import NavbarComponents from "@/components/Navbar/NavbarComponents";
import TabbarComponents from "@/components/Tabbar/TabbarComponents";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Providers>
            <Suspense fallback={""}>
              <ErrorBoundary errorComponent={Error}>
                <header>
                  <NavbarComponents/>
                  <TabbarComponents/>
                </header>
                <main>
                  {children}
                </main>
                <footer>
                  <FooterComponent />
                </footer>
              </ErrorBoundary>
            </Suspense>
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
