import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import StoreProvider from "./StoreProvider";
import { Suspense } from "react";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import FooterComponent from "@/components/FooterComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Providers>
            <Suspense fallback={""}>
              <ErrorBoundary errorComponent={Error}>
                {children}
                <FooterComponent />
              </ErrorBoundary>
            </Suspense>
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
